infix using "C:\Users\HP\Documents\Cspro_2024\CAPI\Exported.dct"

label variable s4q0_a_01 "Code de la source"
label variable s4q0_a_02 "Code de la source"
label variable s4q0_a_03 "Code de la source"
label variable s4q0_a_04 "Code de la source"
label variable s4q0_a_05 "Code de la source"
label variable s4q0_a_06 "Code de la source"
label variable s4q0_a_07 "Code de la source"
label variable s4q0_a_08 "Code de la source"
label variable s4q0_a_09 "Code de la source"
label variable s4q0_a_10 "Code de la source"
label variable s4q0_a_11 "Code de la source"
label variable s4q0_b_01 "Libellé de la source"
label variable s4q0_b_02 "Libellé de la source"
label variable s4q0_b_03 "Libellé de la source"
label variable s4q0_b_04 "Libellé de la source"
label variable s4q0_b_05 "Libellé de la source"
label variable s4q0_b_06 "Libellé de la source"
label variable s4q0_b_07 "Libellé de la source"
label variable s4q0_b_08 "Libellé de la source"
label variable s4q0_b_09 "Libellé de la source"
label variable s4q0_b_10 "Libellé de la source"
label variable s4q0_b_11 "Libellé de la source"
label variable s4q1_01  "Distance par rapport à la maison"
label variable s4q1_02  "Distance par rapport à la maison"
label variable s4q1_03  "Distance par rapport à la maison"
label variable s4q1_04  "Distance par rapport à la maison"
label variable s4q1_05  "Distance par rapport à la maison"
label variable s4q1_06  "Distance par rapport à la maison"
label variable s4q1_07  "Distance par rapport à la maison"
label variable s4q1_08  "Distance par rapport à la maison"
label variable s4q1_09  "Distance par rapport à la maison"
label variable s4q1_10  "Distance par rapport à la maison"
label variable s4q1_11  "Distance par rapport à la maison"
label variable s4q2_01  "Disponibilité( nombre de mois)"
label variable s4q2_02  "Disponibilité( nombre de mois)"
label variable s4q2_03  "Disponibilité( nombre de mois)"
label variable s4q2_04  "Disponibilité( nombre de mois)"
label variable s4q2_05  "Disponibilité( nombre de mois)"
label variable s4q2_06  "Disponibilité( nombre de mois)"
label variable s4q2_07  "Disponibilité( nombre de mois)"
label variable s4q2_08  "Disponibilité( nombre de mois)"
label variable s4q2_09  "Disponibilité( nombre de mois)"
label variable s4q2_10  "Disponibilité( nombre de mois)"
label variable s4q2_11  "Disponibilité( nombre de mois)"
label variable s4q3_01  "Usage"
label variable s4q3_02  "Usage"
label variable s4q3_03  "Usage"
label variable s4q3_04  "Usage"
label variable s4q3_05  "Usage"
label variable s4q3_06  "Usage"
label variable s4q3_07  "Usage"
label variable s4q3_08  "Usage"
label variable s4q3_09  "Usage"
label variable s4q3_10  "Usage"
label variable s4q3_11  "Usage"
label variable s4q3_a_01 "Autre usage"
label variable s4q3_a_02 "Autre usage"
label variable s4q3_a_03 "Autre usage"
label variable s4q3_a_04 "Autre usage"
label variable s4q3_a_05 "Autre usage"
label variable s4q3_a_06 "Autre usage"
label variable s4q3_a_07 "Autre usage"
label variable s4q3_a_08 "Autre usage"
label variable s4q3_a_09 "Autre usage"
label variable s4q3_a_10 "Autre usage"
label variable s4q3_a_11 "Autre usage"
