DATA LIST FILE='C:\USERS\HP\DOCUMENTS\CSPRO_2024\CAPI\SECTION_1.DAT' RECORDS=1
 /
 S0Q1        1-2   
 S0Q2        3-4   
 S0Q3        5-7   
 S0Q4        8-12  
 S1Q1$01    13-14  
 S1Q1$02    15-16  
 S1Q1$03    17-18  
 S1Q1$04    19-20  
 S1Q1$05    21-22  
 S1Q1$06    23-24  
 S1Q1$07    25-26  
 S1Q1$08    27-28  
 S1Q1$09    29-30  
 S1Q1$10    31-32  
 S1Q1$11    33-34  
 S1Q1$12    35-36  
 S1Q1$13    37-38  
 S1Q1$14    39-40  
 S1Q1$15    41-42  
 S1Q1$16    43-44  
 S1Q1$17    45-46  
 S1Q1$18    47-48  
 S1Q1$19    49-50  
 S1Q1$20    51-52  
 S1Q1$21    53-54  
 S1Q1$22    55-56  
 S1Q1$23    57-58  
 S1Q1$24    59-60  
 S1Q1$25    61-62  
 S1Q2$01    63-82   (A)
 S1Q2$02    83-102  (A)
 S1Q2$03   103-122  (A)
 S1Q2$04   123-142  (A)
 S1Q2$05   143-162  (A)
 S1Q2$06   163-182  (A)
 S1Q2$07   183-202  (A)
 S1Q2$08   203-222  (A)
 S1Q2$09   223-242  (A)
 S1Q2$10   243-262  (A)
 S1Q2$11   263-282  (A)
 S1Q2$12   283-302  (A)
 S1Q2$13   303-322  (A)
 S1Q2$14   323-342  (A)
 S1Q2$15   343-362  (A)
 S1Q2$16   363-382  (A)
 S1Q2$17   383-402  (A)
 S1Q2$18   403-422  (A)
 S1Q2$19   423-442  (A)
 S1Q2$20   443-462  (A)
 S1Q2$21   463-482  (A)
 S1Q2$22   483-502  (A)
 S1Q2$23   503-522  (A)
 S1Q2$24   523-542  (A)
 S1Q2$25   543-562  (A)
 S1Q3$01   563-563 
 S1Q3$02   564-564 
 S1Q3$03   565-565 
 S1Q3$04   566-566 
 S1Q3$05   567-567 
 S1Q3$06   568-568 
 S1Q3$07   569-569 
 S1Q3$08   570-570 
 S1Q3$09   571-571 
 S1Q3$10   572-572 
 S1Q3$11   573-573 
 S1Q3$12   574-574 
 S1Q3$13   575-575 
 S1Q3$14   576-576 
 S1Q3$15   577-577 
 S1Q3$16   578-578 
 S1Q3$17   579-579 
 S1Q3$18   580-580 
 S1Q3$19   581-581 
 S1Q3$20   582-582 
 S1Q3$21   583-583 
 S1Q3$22   584-584 
 S1Q3$23   585-585 
 S1Q3$24   586-586 
 S1Q3$25   587-587 
 S1Q4$01   588-588 
 S1Q4$02   589-589 
 S1Q4$03   590-590 
 S1Q4$04   591-591 
 S1Q4$05   592-592 
 S1Q4$06   593-593 
 S1Q4$07   594-594 
 S1Q4$08   595-595 
 S1Q4$09   596-596 
 S1Q4$10   597-597 
 S1Q4$11   598-598 
 S1Q4$12   599-599 
 S1Q4$13   600-600 
 S1Q4$14   601-601 
 S1Q4$15   602-602 
 S1Q4$16   603-603 
 S1Q4$17   604-604 
 S1Q4$18   605-605 
 S1Q4$19   606-606 
 S1Q4$20   607-607 
 S1Q4$21   608-608 
 S1Q4$22   609-609 
 S1Q4$23   610-610 
 S1Q4$24   611-611 
 S1Q4$25   612-612 
 S1Q5$01   613-614 
 S1Q5$02   615-616 
 S1Q5$03   617-618 
 S1Q5$04   619-620 
 S1Q5$05   621-622 
 S1Q5$06   623-624 
 S1Q5$07   625-626 
 S1Q5$08   627-628 
 S1Q5$09   629-630 
 S1Q5$10   631-632 
 S1Q5$11   633-634 
 S1Q5$12   635-636 
 S1Q5$13   637-638 
 S1Q5$14   639-640 
 S1Q5$15   641-642 
 S1Q5$16   643-644 
 S1Q5$17   645-646 
 S1Q5$18   647-648 
 S1Q5$19   649-650 
 S1Q5$20   651-652 
 S1Q5$21   653-654 
 S1Q5$22   655-656 
 S1Q5$23   657-658 
 S1Q5$24   659-660 
 S1Q5$25   661-662 
 S1Q6$01   663-663 
 S1Q6$02   664-664 
 S1Q6$03   665-665 
 S1Q6$04   666-666 
 S1Q6$05   667-667 
 S1Q6$06   668-668 
 S1Q6$07   669-669 
 S1Q6$08   670-670 
 S1Q6$09   671-671 
 S1Q6$10   672-672 
 S1Q6$11   673-673 
 S1Q6$12   674-674 
 S1Q6$13   675-675 
 S1Q6$14   676-676 
 S1Q6$15   677-677 
 S1Q6$16   678-678 
 S1Q6$17   679-679 
 S1Q6$18   680-680 
 S1Q6$19   681-681 
 S1Q6$20   682-682 
 S1Q6$21   683-683 
 S1Q6$22   684-684 
 S1Q6$23   685-685 
 S1Q6$24   686-686 
 S1Q6$25   687-687 
 S1Q7$01   688-688 
 S1Q7$02   689-689 
 S1Q7$03   690-690 
 S1Q7$04   691-691 
 S1Q7$05   692-692 
 S1Q7$06   693-693 
 S1Q7$07   694-694 
 S1Q7$08   695-695 
 S1Q7$09   696-696 
 S1Q7$10   697-697 
 S1Q7$11   698-698 
 S1Q7$12   699-699 
 S1Q7$13   700-700 
 S1Q7$14   701-701 
 S1Q7$15   702-702 
 S1Q7$16   703-703 
 S1Q7$17   704-704 
 S1Q7$18   705-705 
 S1Q7$19   706-706 
 S1Q7$20   707-707 
 S1Q7$21   708-708 
 S1Q7$22   709-709 
 S1Q7$23   710-710 
 S1Q7$24   711-711 
 S1Q7$25   712-712 
 S1Q8$01   713-714 
 S1Q8$02   715-716 
 S1Q8$03   717-718 
 S1Q8$04   719-720 
 S1Q8$05   721-722 
 S1Q8$06   723-724 
 S1Q8$07   725-726 
 S1Q8$08   727-728 
 S1Q8$09   729-730 
 S1Q8$10   731-732 
 S1Q8$11   733-734 
 S1Q8$12   735-736 
 S1Q8$13   737-738 
 S1Q8$14   739-740 
 S1Q8$15   741-742 
 S1Q8$16   743-744 
 S1Q8$17   745-746 
 S1Q8$18   747-748 
 S1Q8$19   749-750 
 S1Q8$20   751-752 
 S1Q8$21   753-754 
 S1Q8$22   755-756 
 S1Q8$23   757-758 
 S1Q8$24   759-760 
 S1Q8$25   761-762 
 S1Q9$01   763-763  (A)
 S1Q9$02   764-764  (A)
 S1Q9$03   765-765  (A)
 S1Q9$04   766-766  (A)
 S1Q9$05   767-767  (A)
 S1Q9$06   768-768  (A)
 S1Q9$07   769-769  (A)
 S1Q9$08   770-770  (A)
 S1Q9$09   771-771  (A)
 S1Q9$10   772-772  (A)
 S1Q9$11   773-773  (A)
 S1Q9$12   774-774  (A)
 S1Q9$13   775-775  (A)
 S1Q9$14   776-776  (A)
 S1Q9$15   777-777  (A)
 S1Q9$16   778-778  (A)
 S1Q9$17   779-779  (A)
 S1Q9$18   780-780  (A)
 S1Q9$19   781-781  (A)
 S1Q9$20   782-782  (A)
 S1Q9$21   783-783  (A)
 S1Q9$22   784-784  (A)
 S1Q9$23   785-785  (A)
 S1Q9$24   786-786  (A)
 S1Q9$25   787-787  (A)
 S1Q10$01  788-788 
 S1Q10$02  789-789 
 S1Q10$03  790-790 
 S1Q10$04  791-791 
 S1Q10$05  792-792 
 S1Q10$06  793-793 
 S1Q10$07  794-794 
 S1Q10$08  795-795 
 S1Q10$09  796-796 
 S1Q10$10  797-797 
 S1Q10$11  798-798 
 S1Q10$12  799-799 
 S1Q10$13  800-800 
 S1Q10$14  801-801 
 S1Q10$15  802-802 
 S1Q10$16  803-803 
 S1Q10$17  804-804 
 S1Q10$18  805-805 
 S1Q10$19  806-806 
 S1Q10$20  807-807 
 S1Q10$21  808-808 
 S1Q10$22  809-809 
 S1Q10$23  810-810 
 S1Q10$24  811-811 
 S1Q10$25  812-812 
.
VARIABLE LABELS
  S0Q1     "Region de l' enquêté"
 /S0Q2     "Province de l' enquêté"
 /S0Q3     "Départements de l' enquêté"
 /S0Q4     "Numéro du ménage"
 /S1Q1$01  "Numéro du membre de ménage"
 /S1Q1$02  "Numéro du membre de ménage"
 /S1Q1$03  "Numéro du membre de ménage"
 /S1Q1$04  "Numéro du membre de ménage"
 /S1Q1$05  "Numéro du membre de ménage"
 /S1Q1$06  "Numéro du membre de ménage"
 /S1Q1$07  "Numéro du membre de ménage"
 /S1Q1$08  "Numéro du membre de ménage"
 /S1Q1$09  "Numéro du membre de ménage"
 /S1Q1$10  "Numéro du membre de ménage"
 /S1Q1$11  "Numéro du membre de ménage"
 /S1Q1$12  "Numéro du membre de ménage"
 /S1Q1$13  "Numéro du membre de ménage"
 /S1Q1$14  "Numéro du membre de ménage"
 /S1Q1$15  "Numéro du membre de ménage"
 /S1Q1$16  "Numéro du membre de ménage"
 /S1Q1$17  "Numéro du membre de ménage"
 /S1Q1$18  "Numéro du membre de ménage"
 /S1Q1$19  "Numéro du membre de ménage"
 /S1Q1$20  "Numéro du membre de ménage"
 /S1Q1$21  "Numéro du membre de ménage"
 /S1Q1$22  "Numéro du membre de ménage"
 /S1Q1$23  "Numéro du membre de ménage"
 /S1Q1$24  "Numéro du membre de ménage"
 /S1Q1$25  "Numéro du membre de ménage"
 /S1Q2$01  "Noms et prénoms"
 /S1Q2$02  "Noms et prénoms"
 /S1Q2$03  "Noms et prénoms"
 /S1Q2$04  "Noms et prénoms"
 /S1Q2$05  "Noms et prénoms"
 /S1Q2$06  "Noms et prénoms"
 /S1Q2$07  "Noms et prénoms"
 /S1Q2$08  "Noms et prénoms"
 /S1Q2$09  "Noms et prénoms"
 /S1Q2$10  "Noms et prénoms"
 /S1Q2$11  "Noms et prénoms"
 /S1Q2$12  "Noms et prénoms"
 /S1Q2$13  "Noms et prénoms"
 /S1Q2$14  "Noms et prénoms"
 /S1Q2$15  "Noms et prénoms"
 /S1Q2$16  "Noms et prénoms"
 /S1Q2$17  "Noms et prénoms"
 /S1Q2$18  "Noms et prénoms"
 /S1Q2$19  "Noms et prénoms"
 /S1Q2$20  "Noms et prénoms"
 /S1Q2$21  "Noms et prénoms"
 /S1Q2$22  "Noms et prénoms"
 /S1Q2$23  "Noms et prénoms"
 /S1Q2$24  "Noms et prénoms"
 /S1Q2$25  "Noms et prénoms"
 /S1Q3$01  "Lien avec le CM"
 /S1Q3$02  "Lien avec le CM"
 /S1Q3$03  "Lien avec le CM"
 /S1Q3$04  "Lien avec le CM"
 /S1Q3$05  "Lien avec le CM"
 /S1Q3$06  "Lien avec le CM"
 /S1Q3$07  "Lien avec le CM"
 /S1Q3$08  "Lien avec le CM"
 /S1Q3$09  "Lien avec le CM"
 /S1Q3$10  "Lien avec le CM"
 /S1Q3$11  "Lien avec le CM"
 /S1Q3$12  "Lien avec le CM"
 /S1Q3$13  "Lien avec le CM"
 /S1Q3$14  "Lien avec le CM"
 /S1Q3$15  "Lien avec le CM"
 /S1Q3$16  "Lien avec le CM"
 /S1Q3$17  "Lien avec le CM"
 /S1Q3$18  "Lien avec le CM"
 /S1Q3$19  "Lien avec le CM"
 /S1Q3$20  "Lien avec le CM"
 /S1Q3$21  "Lien avec le CM"
 /S1Q3$22  "Lien avec le CM"
 /S1Q3$23  "Lien avec le CM"
 /S1Q3$24  "Lien avec le CM"
 /S1Q3$25  "Lien avec le CM"
 /S1Q4$01  "Sexe du membre"
 /S1Q4$02  "Sexe du membre"
 /S1Q4$03  "Sexe du membre"
 /S1Q4$04  "Sexe du membre"
 /S1Q4$05  "Sexe du membre"
 /S1Q4$06  "Sexe du membre"
 /S1Q4$07  "Sexe du membre"
 /S1Q4$08  "Sexe du membre"
 /S1Q4$09  "Sexe du membre"
 /S1Q4$10  "Sexe du membre"
 /S1Q4$11  "Sexe du membre"
 /S1Q4$12  "Sexe du membre"
 /S1Q4$13  "Sexe du membre"
 /S1Q4$14  "Sexe du membre"
 /S1Q4$15  "Sexe du membre"
 /S1Q4$16  "Sexe du membre"
 /S1Q4$17  "Sexe du membre"
 /S1Q4$18  "Sexe du membre"
 /S1Q4$19  "Sexe du membre"
 /S1Q4$20  "Sexe du membre"
 /S1Q4$21  "Sexe du membre"
 /S1Q4$22  "Sexe du membre"
 /S1Q4$23  "Sexe du membre"
 /S1Q4$24  "Sexe du membre"
 /S1Q4$25  "Sexe du membre"
 /S1Q5$01  "Âge du répondant"
 /S1Q5$02  "Âge du répondant"
 /S1Q5$03  "Âge du répondant"
 /S1Q5$04  "Âge du répondant"
 /S1Q5$05  "Âge du répondant"
 /S1Q5$06  "Âge du répondant"
 /S1Q5$07  "Âge du répondant"
 /S1Q5$08  "Âge du répondant"
 /S1Q5$09  "Âge du répondant"
 /S1Q5$10  "Âge du répondant"
 /S1Q5$11  "Âge du répondant"
 /S1Q5$12  "Âge du répondant"
 /S1Q5$13  "Âge du répondant"
 /S1Q5$14  "Âge du répondant"
 /S1Q5$15  "Âge du répondant"
 /S1Q5$16  "Âge du répondant"
 /S1Q5$17  "Âge du répondant"
 /S1Q5$18  "Âge du répondant"
 /S1Q5$19  "Âge du répondant"
 /S1Q5$20  "Âge du répondant"
 /S1Q5$21  "Âge du répondant"
 /S1Q5$22  "Âge du répondant"
 /S1Q5$23  "Âge du répondant"
 /S1Q5$24  "Âge du répondant"
 /S1Q5$25  "Âge du répondant"
 /S1Q6$01  "Situation matrimoniale"
 /S1Q6$02  "Situation matrimoniale"
 /S1Q6$03  "Situation matrimoniale"
 /S1Q6$04  "Situation matrimoniale"
 /S1Q6$05  "Situation matrimoniale"
 /S1Q6$06  "Situation matrimoniale"
 /S1Q6$07  "Situation matrimoniale"
 /S1Q6$08  "Situation matrimoniale"
 /S1Q6$09  "Situation matrimoniale"
 /S1Q6$10  "Situation matrimoniale"
 /S1Q6$11  "Situation matrimoniale"
 /S1Q6$12  "Situation matrimoniale"
 /S1Q6$13  "Situation matrimoniale"
 /S1Q6$14  "Situation matrimoniale"
 /S1Q6$15  "Situation matrimoniale"
 /S1Q6$16  "Situation matrimoniale"
 /S1Q6$17  "Situation matrimoniale"
 /S1Q6$18  "Situation matrimoniale"
 /S1Q6$19  "Situation matrimoniale"
 /S1Q6$20  "Situation matrimoniale"
 /S1Q6$21  "Situation matrimoniale"
 /S1Q6$22  "Situation matrimoniale"
 /S1Q6$23  "Situation matrimoniale"
 /S1Q6$24  "Situation matrimoniale"
 /S1Q6$25  "Situation matrimoniale"
 /S1Q7$01  "Religion du membre"
 /S1Q7$02  "Religion du membre"
 /S1Q7$03  "Religion du membre"
 /S1Q7$04  "Religion du membre"
 /S1Q7$05  "Religion du membre"
 /S1Q7$06  "Religion du membre"
 /S1Q7$07  "Religion du membre"
 /S1Q7$08  "Religion du membre"
 /S1Q7$09  "Religion du membre"
 /S1Q7$10  "Religion du membre"
 /S1Q7$11  "Religion du membre"
 /S1Q7$12  "Religion du membre"
 /S1Q7$13  "Religion du membre"
 /S1Q7$14  "Religion du membre"
 /S1Q7$15  "Religion du membre"
 /S1Q7$16  "Religion du membre"
 /S1Q7$17  "Religion du membre"
 /S1Q7$18  "Religion du membre"
 /S1Q7$19  "Religion du membre"
 /S1Q7$20  "Religion du membre"
 /S1Q7$21  "Religion du membre"
 /S1Q7$22  "Religion du membre"
 /S1Q7$23  "Religion du membre"
 /S1Q7$24  "Religion du membre"
 /S1Q7$25  "Religion du membre"
 /S1Q8$01  "Ethnie du membre"
 /S1Q8$02  "Ethnie du membre"
 /S1Q8$03  "Ethnie du membre"
 /S1Q8$04  "Ethnie du membre"
 /S1Q8$05  "Ethnie du membre"
 /S1Q8$06  "Ethnie du membre"
 /S1Q8$07  "Ethnie du membre"
 /S1Q8$08  "Ethnie du membre"
 /S1Q8$09  "Ethnie du membre"
 /S1Q8$10  "Ethnie du membre"
 /S1Q8$11  "Ethnie du membre"
 /S1Q8$12  "Ethnie du membre"
 /S1Q8$13  "Ethnie du membre"
 /S1Q8$14  "Ethnie du membre"
 /S1Q8$15  "Ethnie du membre"
 /S1Q8$16  "Ethnie du membre"
 /S1Q8$17  "Ethnie du membre"
 /S1Q8$18  "Ethnie du membre"
 /S1Q8$19  "Ethnie du membre"
 /S1Q8$20  "Ethnie du membre"
 /S1Q8$21  "Ethnie du membre"
 /S1Q8$22  "Ethnie du membre"
 /S1Q8$23  "Ethnie du membre"
 /S1Q8$24  "Ethnie du membre"
 /S1Q8$25  "Ethnie du membre"
 /S1Q9$01  "Langues parlées par le membre"
 /S1Q9$02  "Langues parlées par le membre"
 /S1Q9$03  "Langues parlées par le membre"
 /S1Q9$04  "Langues parlées par le membre"
 /S1Q9$05  "Langues parlées par le membre"
 /S1Q9$06  "Langues parlées par le membre"
 /S1Q9$07  "Langues parlées par le membre"
 /S1Q9$08  "Langues parlées par le membre"
 /S1Q9$09  "Langues parlées par le membre"
 /S1Q9$10  "Langues parlées par le membre"
 /S1Q9$11  "Langues parlées par le membre"
 /S1Q9$12  "Langues parlées par le membre"
 /S1Q9$13  "Langues parlées par le membre"
 /S1Q9$14  "Langues parlées par le membre"
 /S1Q9$15  "Langues parlées par le membre"
 /S1Q9$16  "Langues parlées par le membre"
 /S1Q9$17  "Langues parlées par le membre"
 /S1Q9$18  "Langues parlées par le membre"
 /S1Q9$19  "Langues parlées par le membre"
 /S1Q9$20  "Langues parlées par le membre"
 /S1Q9$21  "Langues parlées par le membre"
 /S1Q9$22  "Langues parlées par le membre"
 /S1Q9$23  "Langues parlées par le membre"
 /S1Q9$24  "Langues parlées par le membre"
 /S1Q9$25  "Langues parlées par le membre"
 /S1Q10$01 "Langue principale parlée"
 /S1Q10$02 "Langue principale parlée"
 /S1Q10$03 "Langue principale parlée"
 /S1Q10$04 "Langue principale parlée"
 /S1Q10$05 "Langue principale parlée"
 /S1Q10$06 "Langue principale parlée"
 /S1Q10$07 "Langue principale parlée"
 /S1Q10$08 "Langue principale parlée"
 /S1Q10$09 "Langue principale parlée"
 /S1Q10$10 "Langue principale parlée"
 /S1Q10$11 "Langue principale parlée"
 /S1Q10$12 "Langue principale parlée"
 /S1Q10$13 "Langue principale parlée"
 /S1Q10$14 "Langue principale parlée"
 /S1Q10$15 "Langue principale parlée"
 /S1Q10$16 "Langue principale parlée"
 /S1Q10$17 "Langue principale parlée"
 /S1Q10$18 "Langue principale parlée"
 /S1Q10$19 "Langue principale parlée"
 /S1Q10$20 "Langue principale parlée"
 /S1Q10$21 "Langue principale parlée"
 /S1Q10$22 "Langue principale parlée"
 /S1Q10$23 "Langue principale parlée"
 /S1Q10$24 "Langue principale parlée"
 /S1Q10$25 "Langue principale parlée"
.
VALUE LABELS
  S0Q1    
     1 "Boucle du Mouhoun"
     2 "Cascade"
     3 "Centre"
     4 "Centre-Est"
     5 "Centre-Nord"
     6 "Centre-Ouest"
     7 "Centre-Sud"
     8 "Est"
     9 "Haut-Bassin"
    10 "Nord"
    11 "Plateau-Central"
    12 "Sahel"
    13 "Sud-Ouest"
 /S0Q2    
     1 "Balé"
     2 "Banwa"
     3 "Kossi"
     4 "Mouhoun"
     5 "Nayala"
     6 "Sourou"
 /S0Q3    
     1 "Bagassi"
     2 "Bana"
     3 "Boromo"
     4 "Fara"
     5 "Oury"
     6 "Pâ"
     7 "Pompoie"
     8 "Poura"
     9 "Sibi"
    10 "Yaho"
 /S1Q3$01 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$02 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$03 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$04 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$05 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$06 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$07 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$08 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$09 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$10 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$11 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$12 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$13 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$14 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$15 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$16 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$17 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$18 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$19 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$20 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$21 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$22 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$23 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$24 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q3$25 
     1 " CM"
     2 "Conjoint(e) du CM"
     3 "Fils/Fille du CM"
     4 "Frère/Soeur du CM"
     5 "Parent(e) du CM"
     6 "Aucun lien"
     7 "Autre (à préciser)"
 /S1Q4$01 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$02 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$03 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$04 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$05 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$06 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$07 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$08 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$09 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$10 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$11 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$12 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$13 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$14 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$15 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$16 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$17 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$18 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$19 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$20 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$21 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$22 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$23 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$24 
     0 "Masculin"
     1 "Féminin"
 /S1Q4$25 
     0 "Masculin"
     1 "Féminin"
 /S1Q6$01 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$02 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$03 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$04 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$05 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$06 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$07 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$08 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$09 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$10 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$11 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$12 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$13 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$14 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$15 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$16 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$17 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$18 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$19 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$20 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$21 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$22 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$23 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$24 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q6$25 
     1 "Célibataire"
     2 "Marié(e) monogame"
     3 "Marié(e) polygame"
     4 "Union libre"
     5 "Divorcé"
     6 "Veuf(ve)"
     7 "Autre à préciser"
 /S1Q7$01 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$02 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$03 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$04 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$05 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$06 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$07 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$08 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$09 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$10 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$11 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$12 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$13 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$14 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$15 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$16 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$17 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$18 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$19 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$20 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$21 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$22 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$23 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$24 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q7$25 
     1 "Islam"
     2 "Catholicisme"
     3 "Protestantisme"
     4 "Animiste"
     5 "Athéisme"
     6 "Autres (à préciser)"
 /S1Q8$01 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$02 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$03 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$04 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$05 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$06 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$07 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$08 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$09 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$10 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$11 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$12 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$13 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$14 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$15 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$16 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$17 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$18 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$19 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$20 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$21 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$22 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$23 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$24 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q8$25 
     1 "Mossi"
     2 "Peulh"
     3 "Bobo"
     4 "Samo"
     5 "Bissa"
     6 "Gourmantché"
     7 "Gourounssi"
     8 "Dagara"
     9 "Lobi"
    10 "Sénoufo"
    11 "Bwaba"
    12 "Autre à préciser"
 /S1Q9$01 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$02 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$03 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$04 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$05 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$06 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$07 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$08 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$09 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$10 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$11 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$12 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$13 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$14 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$15 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$16 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$17 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$18 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$19 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$20 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$21 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$22 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$23 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$24 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q9$25 
  1 "Français"
  2 "Anglais"
  3 "Moore"
  4 "Fulfudé"
  5 "Dioula"
  6 "Autre Langues nationales(à préciser)"
  7 "Autre Langues africaines (à préciser)"
  8 "Autre Langues internationales(à préciser)"
 /S1Q10$01
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$02
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$03
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$04
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$05
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$06
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$07
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$08
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$09
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$10
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$11
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$12
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$13
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$14
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$15
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$16
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$17
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$18
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$19
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$20
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$21
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$22
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$23
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$24
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
 /S1Q10$25
     1 "Français"
     2 "Anglais"
     3 "Moore"
     4 "Fulfudé"
     5 "Dioula"
     6 "Autre Langues nationales(à préciser)"
     7 "Autre Langues africaines (à préciser)"
     8 "Autre Langues internationales(à préciser)"
.
EXECUTE.
